version: '3.3'
services:
  spp-platform:
    image: sourceplusplus/spp-platform:0.5.4
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5450:5450"
      - "5455:5455"
      - "12800:12800"
    environment:
      - SPP_OAP_HOST=skywalking-oap
      - SPP_HTTP_SSL_ENABLED=false
      - SPP_JWT_ENABLED=false
  skywalking-oap:
    image: sourceplusplus/spp-oap-server:0.5.4
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
    restart: on-failure
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_HTTP_SSL_ENABLED=false
