version: '3.3'
services:
  spp-platform:
    image: sourceplusplus/spp-platform:0.3.1
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "5445:5445"
      - "5450:5450"
      - "5455:5455"
    depends_on:
      - redis
    links:
      - redis
    restart: on-failure
    environment:
      - CLUSTER_URL=localhost
      - CLUSTER_NAME=docker
      - SPP_REDIS_HOST=redis
      - SPP_SKYWALKING_HOST=skywalking-oap
      - SPP_DISABLE_TLS=true
      - SPP_DISABLE_JWT=true
  redis:
    image: redis:6.2.1
    container_name: redis
    hostname: redis
  skywalking-oap:
    image: sourceplusplus/spp-oap-server:0.3.1
    container_name: skywalking-oap
    hostname: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    restart: on-failure
    environment:
      - SPP_PLATFORM_HOST=spp-platform
      - SPP_PLATFORM_PORT=5460
      - SPP_DISABLE_TLS=true
